# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec9c20a7c1e7d87102a34f9bbab040c33e0e09ed7efd46aa7bd303114e12d556f9bc3dc2e0175033873e52071c25140e2aa1a0c8b046dabf66c87987c65f78e1

test:
  secret_key_base: 674baf7d05231696b49a292ad874ca4fc403406ab3df2e3c13ecbb70ca1e60f4bf6074d33b8e98bf92aa280e6e174f8921f32fa4e63c87f08ff6c616fca3ef9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
